name: Daily Project Update

on:
  schedule:
    - cron: "30 17 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency: daily-update

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Make daily update
        run: |
          echo "Last automated update: $(date -u)" > DAILY_STATUS.md

      - name: Commit changes
        run: |
          git config user.name "atharvk-43"
          git config user.email "atharvkrishna24@gmail.com"

          git add DAILY_STATUS.md

          git diff --cached --quiet || git commit -m "chore: daily project update"

          git push
